prgrms-web-devcourse-final-project/WEB2_3_CUBE_BE

roome/.gitignore, roome/build.gradle, roome/src/main/java/com/roome/domain/oauth2/dto/GoogleResponse.java, roome/src/main/java/com/roome/domain/oauth2/dto/KakaoResponse.java, roome/src/main/java/com/roome/domain/oauth2/dto/NaverResponse.java, roome/src/main/java/com/roome/domain/oauth2/dto/OAuth2Provider.java, roome/src/main/java/com/roome/domain/oauth2/dto/OAuth2Response.java, roome/src/main/java/com/roome/domain/oauth2/dto/OAuth2UserPrincipal.java, roome/src/main/java/com/roome/domain/oauth2/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/resources/application.yml
Feat: 소셜 로그인 기본 기능 구현
소셜 로그인 (Google, Naver, Kakao) 기본 기능을 구현하였습니다.
현재 로그인 창까지 정상적으로 동작하도록 구성하였으며, 이후 JWT 발급 및 인증 로직을 추가할 예정입니다.
#1 
=> Feat: 소셜 로그인 기본 기능 구현

roome/src/main/java/com/roome/domain/furniture/entity/Furniture.java, roome/src/main/java/com/roome/domain/furniture/entity/FurnitureType.java, roome/src/main/java/com/roome/domain/furniture/repository/FurnitureRepository.java, roome/src/main/java/com/roome/domain/room/entity/Room.java
room & furniture 관련 엔티티 추가했습니다.
=> Feat: room & furniture 관련 엔티티 추가

roome/src/main/java/com/roome/domain/furniture/dto/FurnitureResponseDto.java, roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java, roome/src/main/java/com/roome/domain/room/repository/RoomRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
room 관련 응답 dto 추가 및
room 기본 기능 (방 생성 및 조회) 구현했습니다.
=> Feat: room 기본 기능 구현

roome/src/main/java/com/roome/domain/book/entity/Book.java, roome/src/main/java/com/roome/domain/book/entity/repository/BookRepository.java, roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/MyBook.java, roome/src/main/java/com/roome/domain/mybook/entity/MyBookCount.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookCountRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybook/service/request/MyBookCreateRequest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookCountRepositoryTest.java
=> Feat: 도서 등록 API

roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookCountRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/global/util/StringUtil.java
=> Feat: 등록 도서 삭제 API

roome/src/main/java/com/roome/domain/mybook/entity/MyBook.java, roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/entity/CoverColor.java, roome/src/main/java/com/roome/domain/mybookreview/entity/MyBookReview.java, roome/src/main/java/com/roome/domain/mybookreview/entity/repository/MyBookReviewRepository.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewCreateRequest.java, roome/src/main/java/com/roome/domain/mybookreview/service/response/MyBookReviewResponse.java
- feat: 서평을 등록하려는 사용자가 해당 책을 등록한 사용자가 아니라면 예외 처리
서평 등록 기능
=> Feat: 서평 등록 기능 구현

roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/entity/repository/MyBookReviewRepository.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java
=> Feat: 서평 조회 API

roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewUpdateRequest.java
=> Feat: 서평 수정 API

roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java
=> Feat: 서평 삭제 API

roome/src/main/java/com/roome/domain/mybookreview/entity/repository/MyBookReviewRepository.java, roome/src/main/java/com/roome/domain/mybookreview/exception/DoNotHavePermissionToReviewException.java, roome/src/main/java/com/roome/domain/mybookreview/exception/MyBookReviewNotFoundException.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
=> Refactor: 서평 예외 처리

roome/src/main/java/com/roome/domain/mybook/exception/DoNotHavePermissionToMyBookException.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
=> Refactor: 등록 도서 예외 처리

roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/repository/RoomRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
room - user 연결 및 user id로 방 찾기 기능 추가했습니다.
=> Feat: room - user 연결 및 user id로 방 찾기 기능 추가

roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/exception/MyBookNotFoundException.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/exception/DoNotHavePermissionToRoomException.java, roome/src/main/java/com/roome/domain/room/exception/RoomNoFoundException.java, roome/src/main/java/com/roome/domain/room/repository/RoomRepository.java, roome/src/main/java/com/roome/domain/user/repository/UserRepository.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
=> Feat: 예외 추가, 검증 추가, userId를 request header의 accessToken으로 얻도록 변경

roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java
=> Feat: userId를 request header의 accessToken으로 얻도록 변경, 조회 api 수정

roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java
=> Fix: room 조회 시 userId로 조회하던 걸 roomId로 조회하도록 수정

roome/src/test/java/com/roome/mybook/entity/repository/MyBookCountRepositoryTest.java, roome/src/test/java/com/roome/mybook/entity/repository/MyBookRepositoryTest.java, roome/src/test/java/com/roome/mybook/service/MyBookServiceTest.java
=> Test: MyBook 테스트코드 작성

roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/main/java/com/roome/global/exception/ErrorResponse.java, roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2FailureHandler.java
refactor: 에러 응답에서 HTTP 상태 코드 문자열 제거
refactor: 에러 응답에서 HTTP 상태 코드 문자열 제거
=> refactor: 에러 응답에서 HTTP 상태 코드 문자열 제거

roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java
=> feat: userId 검증 로직 추가

roome/src/main/java/com/roome/domain/book/entity/Book.java, roome/src/main/java/com/roome/domain/book/entity/BookGenre.java, roome/src/main/java/com/roome/domain/book/entity/Genre.java, roome/src/main/java/com/roome/domain/book/entity/repository/GenreRepository.java, roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/MyBook.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybook/service/request/MyBookCreateRequest.java, roome/src/main/java/com/roome/domain/mybook/service/response/MyBookResponse.java, roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/test/java/com/roome/domain/mybook/controller/MyBookControllerTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookRepositoryTest.java, roome/src/test/java/com/roome/domain/mybook/service/MyBookServiceTest.java, roome/src/test/java/com/roome/domain/mybookreview/service/MyBookReviewServiceTest.java
=> Feat: 도서 장르 추가, MyBookController 테스트 코드 추가, Controller에서 accessToken으로 userId 얻는 부분 삭제

roome/src/main/java/com/roome/domain/mybookreview/entity/MyBookReview.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewCreateRequest.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewUpdateRequest.java, roome/src/test/java/com/roome/domain/mybook/controller/MyBookControllerTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookCountRepositoryTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookRepositoryTest.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
=> Test: MyBookReviewController 테스트코드 작성

roome/src/main/java/com/roome/domain/mybookreview/controller/MockMyBookReviewController.java
=> Feat: MyBookReview Mock API

roome/src/main/java/com/roome/domain/cd/entity/Cd.java, roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java, roome/src/main/java/com/roome/domain/mycd/dto/MyCdResponse.java
=> feat: MyCd Mock API 구현

roome/src/main/java/com/roome/domain/cdcomment/controller/MockCdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentCreateRequest.java, roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentListResponse.java, roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentResponse.java
=> feat: CdComment Mock API 구현

roome/src/main/java/com/roome/domain/furniture/dto/FurnitureResponseDto.java, roome/src/main/java/com/roome/domain/furniture/entity/Furniture.java, roome/src/main/java/com/roome/domain/furniture/entity/FurnitureCapacity.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java, roome/src/main/java/com/roome/domain/room/dto/StorageLimitsDto.java, roome/src/main/java/com/roome/domain/room/dto/UserStorageDto.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/entity/RoomTheme.java, roome/src/main/java/com/roome/domain/room/repository/RoomRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
방 조회 응답 구조 변경 및 가구 레벨 별 저장 용량 추가
=> Feat: 방 조회 응답 구조 변경 및 가구 레벨 별 저장 용량 추가

roome/src/main/java/com/roome/domain/furniture/dto/FurnitureResponseDto.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/dto/StorageLimitsDto.java, roome/src/main/java/com/roome/domain/room/dto/UserStorageDto.java
=> Feat: Room Mock Api 추가

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookListResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookRequestDto.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/dto/PaginationDto.java, roome/src/main/java/com/roome/domain/guestbook/entity/Guestbook.java, roome/src/main/java/com/roome/domain/guestbook/entity/RelationType.java, roome/src/main/java/com/roome/domain/guestbook/repository/GuestbookRepository.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
=> Feat: 방명록 기능 추가

roome/src/main/java/com/roome/domain/book/entity/repository/BookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
=> Feat: 도서 저장시 isbn으로 DB에 동일한 도서가 있는지 확인, MyBookReviewController 테스트코드 수정

roome/src/main/java/com/roome/domain/guestbook/controller/MockGuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookListResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/dto/PaginationDto.java
=> Feat: 방명록 Mock Api 추가

roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
=> feat: cd 삭제 API

roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java, roome/src/main/java/com/roome/domain/mycd/dto/MyCdListResponse.java, roome/src/main/java/com/roome/domain/mycd/dto/MyCdResponse.java
=> refactor: MyCd Mock API 리팩토링

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
- CdCommentController
- CdCommentRepository
- CdCommentService
=> feat: CD 댓글 목록 조회 API 구현

roome/src/main/java/com/roome/domain/book/entity/repository/BookRepository.java, roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/MyBookCount.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookCountRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/entity/MyBookReview.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewCreateRequest.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewUpdateRequest.java, roome/src/test/java/com/roome/domain/mybook/controller/MyBookControllerTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookCountRepositoryTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookRepositoryTest.java, roome/src/test/java/com/roome/domain/mybook/service/MyBookServiceTest.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
=> Feat: 도서, 서평 url 수정

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
=> feat: CD 댓글 삭제 API 구현

roome/src/main/java/com/roome/domain/mybookreview/controller/MockMyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/entity/MyBookReview.java, roome/src/main/java/com/roome/domain/mybookreview/service/request/MyBookReviewCreateRequest.java, roome/src/main/java/com/roome/domain/mybookreview/service/response/MyBookReviewResponse.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java, roome/src/test/java/com/roome/domain/mybookreview/service/MyBookReviewServiceTest.java
=> Feat: 서평 작성일자 추가

roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/exception/MyBookDuplicateException.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/room/repository/RoomRepository.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/test/java/com/roome/domain/mybook/service/MyBookServiceTest.java
=> Feat: 이미 책장에 등록되어 있는 도서를 등록하려는 경우 예외 처리

roome/src/main/java/com/roome/domain/book/entity/Book.java, roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/exception/MyBookReviewDuplicateException.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/test/java/com/roome/domain/mybookreview/service/MyBookReviewServiceTest.java
=> Feat: 서평 등록시 중복 등록인지 확인하는 예외 처리

roome/src/main/java/com/roome/domain/mycd/dto/MyCdCreateRequest.java, roome/src/test/java/com/roome/domain/mycd/controller/MyCdControllerTest.java, roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
- MyCdControllerTest
- MyCdServiceTest
=> test: MyCd 테스트 코드 작성

roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentCreateRequest.java, roome/src/main/java/com/roome/domain/cdcomment/entity/CdComment.java, roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java, roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java, roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
- CdCommentControllerTest
- CdCommentServiceTest
=> test: CdComment 테스트 코드 작성

roome/src/main/java/com/roome/domain/notification/controller/MockNotificationController.java, roome/src/main/java/com/roome/domain/notification/controller/NotificationController.java, roome/src/main/java/com/roome/domain/user/controller/MockUserController.java, roome/src/main/java/com/roome/domain/user/controller/UserGenreController.java, roome/src/main/java/com/roome/domain/user/controller/UserProfileController.java, roome/src/main/java/com/roome/domain/user/dto/request/MockUpdateProfileRequest.java, roome/src/main/java/com/roome/domain/user/dto/request/UpdateProfileRequest.java, roome/src/main/java/com/roome/domain/user/dto/response/UserProfileResponse.java, roome/src/main/java/com/roome/domain/user/entity/BookGenre.java, roome/src/main/java/com/roome/domain/user/entity/MusicGenre.java, roome/src/main/java/com/roome/domain/user/entity/UserBookGenre.java, roome/src/main/java/com/roome/domain/user/entity/UserMusicGenre.java, roome/src/main/java/com/roome/domain/user/repository/UserBookGenreRepository.java, roome/src/main/java/com/roome/domain/user/repository/UserMusicGenreRepository.java, roome/src/main/java/com/roome/domain/user/service/UserGenreService.java, roome/src/main/java/com/roome/domain/user/service/UserProfileService.java, roome/src/main/java/com/roome/global/config/S3Config.java, roome/src/main/java/com/roome/global/controller/FileController.java, roome/src/main/java/com/roome/global/dto/s3/FileResponse.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/main/java/com/roome/global/service/S3Service.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/user/controller/MockUserControllerTest.java, roome/src/test/java/com/roome/domain/user/controller/UserGenreControllerTest.java, roome/src/test/java/com/roome/domain/user/controller/UserProfileControllerTest.java, roome/src/test/java/com/roome/domain/user/service/UserProfileServiceTest.java
feat 프로필 조회 api 기능
음악 감성 추가(최대 3개) 기능
독서 취향 선택(최대 3개) 기능
비슷한 취향 추천(5명) 기능
프로필 수정 기능(한 줄 소개, 닉네임, 프로필 이미지)
음악 감성 추가(최대 3개) 기능
독서 취향 선택(최대 3개) 기능
비슷한 취향 추천(5명) 기능
프로필 수정 기능(한 줄 소개, 닉네임, 프로필 이미지)
=> feat 프로필 조회 api 기능

roome/src/main/java/com/roome/domain/room/dto/UpdateRoomThemeRequestDto.java, roome/src/main/java/com/roome/domain/room/entity/RoomTheme.java, roome/src/test/java/com/roome/domain/room/controller/RoomControllerTest.java, roome/src/test/java/com/roome/domain/room/service/RoomServiceTest.java
=> Feat: room test 코드 작성 및 테마 종류 수정

roome/src/main/java/com/roome/domain/guestbook/entity/Guestbook.java, roome/src/test/java/com/roome/domain/guestbook/controller/GuestbookControllerTest.java, roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceTest.java
=> Test: 방명록 관련 테스트 코드 작성

roome/src/main/java/com/roome/domain/auth/security/OAuth2UserPrincipal.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java, roome/src/test/java/com/roome/domain/auth/service/OAuth2LoginServiceTest.java, roome/src/test/java/com/roome/global/jwt/service/JwtTokenProviderTest.java, roome/src/test/java/com/roome/global/jwt/service/TokenServiceTest.java
=> Fix: JWT 및 OAuth2 로그인 테스트 코드 수정 및 보안 설정 강화

roome/src/main/java/com/roome/domain/auth/service/OAuth2LoginService.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/domain/user/repository/UserRepository.java
=> Feat: 하루 한 번 로그인시 포인트 획득 기능 추가

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/jwt/filter/JwtAuthenticationFilter.java, roome/src/main/java/com/roome/global/jwt/helper/TokenResponseHelper.java, roome/src/main/java/com/roome/global/jwt/service/JwtTokenProvider.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java, roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java, roome/src/test/java/com/roome/global/jwt/service/JwtTokenProviderTest.java
Redis를 활용한 JWT 토큰 관리 시스템을 개선하여 보안성을 강화하고, 토큰 만료 처리 및 오류 처리 로직을 개선했습니다. 환경 설정 값을 외부화하고 코드의 전반적인 품질을 향상시켰습니다.
> JWT 관련 단위 테스트 모두 통과
=> Feat/Fix: 인증/인가 시스템 보안 강화 및 토큰 관리 개선

roome/src/main/java/com/roome/domain/auth/service/OAuth2LoginService.java, roome/src/main/java/com/roome/domain/point/entity/Point.java, roome/src/main/java/com/roome/domain/user/entity/User.java
=> Feat: 사용자 로그인시 하루 한 번 포인트 획득

roome/src/main/java/com/roome/domain/furniture/entity/Furniture.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
가구 활성화 및 비활성화 관련해서 누락되어 있던 코드들 추가했습니다.
=> Feat: 가구 활성화 및 비활성화 관련 코드 추가

roome/src/main/java/com/roome/domain/guestbook/controller/MockGuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookRequestDto.java, roome/src/test/java/com/roome/domain/guestbook/controller/GuestbookControllerTest.java, roome/src/test/java/com/roome/domain/guestbook/controller/MockGuestbookControllerTest.java, roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceTest.java
guestboook 관련 테스트 코드 추가 및 수정했습니다.
=> Test: guestboook 관련 테스트 코드 추가 및 수정

roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/test/java/com/roome/domain/room/controller/MockRoomControllerTest.java, roome/src/test/java/com/roome/domain/room/controller/RoomControllerTest.java, roome/src/test/java/com/roome/domain/room/service/RoomServiceTest.java
=> Refactor: 예외 처리 보완 및 테스트 코드 수정

roome/src/main/java/com/roome/global/config/SecurityConfig.java
=> Fix: cors 설정 수정

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/domain/user/repository/UserRepository.java
=> Feat: 하루 한 번 로그인시 포인트 획득

roome/src/main/java/com/roome/domain/furniture/dto/FurnitureRequestDto.java, roome/src/main/java/com/roome/domain/furniture/dto/ToggleFurnitureResponseDto.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/dto/UpdateRoomThemeResponseDto.java
=> Refactor: 가구 토글 응답 형태 수정

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/main/java/com/roome/domain/furniture/dto/FurnitureRequestDto.java, roome/src/main/java/com/roome/domain/furniture/dto/ToggleFurnitureResponseDto.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/dto/UpdateRoomThemeResponseDto.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/UnauthorizedException.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java, roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
백엔드 포트로 리다이렉트 되는 문제로 redirect uri 프론트엔드 포트로 변경
=> Fix: .yml 포트 변경

roome/src/main/resources/application.yml
=> Fix: .yml redirect uri 변경

roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java, roome/src/main/resources/application.yml
=> Fix: .yml 파일과 SecurityConfig uri 불일치 해결

roome/src/main/resources/application.yml
=> Fix: .yml redirect-uri 수정

roome/src/main/java/com/roome/global/config/SecurityConfig.java
=> Fix: SecurityConfig에서 리디렉션 설정을 application.yml과 같게 만듦

roome/src/main/java/com/roome/domain/point/entity/PointHistory.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java
OAuth 리디렉션 URL에서 userId 파라미터를 제거하고 관계설정을 변경해 에러를 해결하였습니다.
=> Fix: point_history 테이블에서 user 엔티티와의 관계 설정 변경

roome/src/main/java/com/roome/domain/mybookreview/controller/MyBookReviewController.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
=> 서평 API 스웨거 추가, JWT 적용, JWT적용후 깨지는 테스트코드 수정

roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/test/java/com/roome/domain/mybook/controller/MyBookControllerTest.java, roome/src/test/java/com/roome/domain/mybook/service/MyBookServiceTest.java
=> 도서 API 스웨거 설정, 도서 API JWT 적용, 테스트코드 수정

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/rank/controller/RankingController.java, roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/main/java/com/roome/global/jwt/filter/JwtAuthenticationFilter.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java
인증/인가 관련 API 개선, 포인트 시스템 보완, JWT 검증 로직 수정, OAuth2 로그인 기능 개선 및 테스트 코드 추가 등의 작업 수행
=> Test: CustomOAuth2UserService 테스트 코드 추가 및 리팩토링

roome/src/main/java/com/roome/domain/houseMate/controller/HousemateController.java, roome/src/main/java/com/roome/domain/houseMate/controller/MockHouseMateController.java, roome/src/main/java/com/roome/domain/notification/controller/MockNotificationController.java, roome/src/main/java/com/roome/domain/notification/controller/NotificationController.java, roome/src/main/java/com/roome/domain/user/controller/MockUserProfileController.java, roome/src/main/java/com/roome/domain/user/controller/UserProfileController.java, roome/src/main/java/com/roome/domain/user/controller/UserProfileImageController.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/notification/controller/NotificationControllerTest.java, roome/src/test/java/com/roome/domain/user/controller/MockUserControllerTest.java
스웨거 태그 수정 및 이미지 사이즈 수정
- API 스웨거 태그 수정
=> Refactor/171 refactor 알림 알림 기능 수정

roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java
방명록 생성 시 생성 시간 저장 누락된 거 추가했습니다.
=> Fix: 방명록 생성 시 생성 시간 저장 누락된 거 추가

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java
=> Refactor: 스웨거 태그 추가

roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java, roome/src/test/java/com/roome/domain/user/controller/MockUserControllerTest.java, roome/src/test/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandlerTest.java, roome/src/test/java/com/roome/global/jwt/service/TokenServiceTest.java
테스트 코드 변경 및 수정된 코드에 맞춰 테스트 로직을 업데이트했습니다.
=> Test: 코드 변경에 따른 테스트 코드 업데이트

roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/test/java/com/roome/global/jwt/controller/ReissueControllerTest.java
남은 유효 시간이 5분 이하인 액세스 토큰만 재발급 허용
=> Feat: 토큰 재발급 API에 액세스 토큰 검증 로직 추가

.gitignore, roome/src/main/java/com/roome/domain/houseMate/controller/HousemateController.java, roome/src/main/java/com/roome/domain/notification/controller/NotificationController.java, roome/src/main/java/com/roome/domain/user/controller/UserProfileController.java, roome/src/main/java/com/roome/domain/user/controller/UserProfileImageController.java, roome/src/main/java/com/roome/global/config/WebConfig.java, roome/src/main/java/com/roome/global/service/S3Service.java, roome/src/test/java/com/roome/domain/houseMate/controller/HousemateControllerTest.java, roome/src/test/java/com/roome/domain/notification/controller/NotificationControllerTest.java, roome/src/test/java/com/roome/domain/user/controller/UserProfileControllerTest.java, roome/src/test/java/com/roome/domain/user/controller/UserProfileImageControllerTest.java
하우스 메이트, 알림, 프로필 인증 인가 방법 수정 및 테스트 코드 변경
프로필 이미지 빈 파일 업로드 가능하게 변경
cors 설정 도메인 추가.
하우스 메이트, 알림, 프로필 인증 인가 방법 수정 및 테스트 코드 변경
프로필 이미지 빈 파일 업로드 가능하게 변경
cors 설정 도메인 추가.
=> cors 설정 추가 도메인도 추가 되어야함.

.github/workflows/auto-assign-reviewer.yml, .github/workflows/auto-assign.yml
pr 시에 리뷰어 자동 추가 완성
pr 시에 리뷰어 자동 추가 완성
=> pr 시에 리뷰어 자동 추가 완성

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/controller/MockCdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentCreateRequest.java, roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentResponse.java, roome/src/main/java/com/roome/domain/cdcomment/entity/CdComment.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/main/java/com/roome/global/exception/ForbiddenException.java, roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java, roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
=> Refactor: CD 댓글 삭제 권한 로직 수정 및 타임스탬프 필드 변경

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java
로그인 과정에서 같은 이메일이라도 provider가 다르면 새로운 계정을 생성하도록 수정하고, 이에 맞춰 테스트 코드도 보완했습니다.
=> Fix: 로그인 로직 수정 및 테스트 개선

roome/src/main/java/com/roome/domain/user/entity/User.java
기존 unique = true 제거하여 중복 email 허용
=> Fix: User 엔티티에서 email의 unique 제약 제거

roome/src/main/java/com/roome/domain/guestbook/entity/Guestbook.java
=> Fix: 방명록 작성 시 시간이 null인거 저장되는거 수정

roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
- 기존 페이지네이션이 0부터 시작하여 사용자 경험과 맞지 않는 문제 수정
- 클라이언트가 1부터 요청하면 내부적으로 0부터 처리되도록 로직 변경
- 응답 시 페이지 번호를 +1 하여 UI와 일관성을 유지
=> fix: 페이지 번호 1부터 시작하도록 변경

roome/src/main/java/com/roome/domain/furniture/entity/Furniture.java, roome/src/main/java/com/roome/domain/user/entity/User.java
=> Fix: 가구 자동 생성되게 수정

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
=> fix: 페이지네이션 1부터 시작하도록 수정

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/test/java/com/roome/domain/guestbook/controller/GuestbookControllerTest.java
방명록 추가 시 방명록 조회를 호출해서 응답하도록 수정
=> Fix: 방명록 추가 시 방명록 조회를 호출해서 응답하도록 수정

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/main/java/com/roome/domain/user/entity/User.java
=> Fix: 방 생성 시 가구 자동 추가되도록 수정

.github/workflows/auto-assign.yml, roome/build.gradle, roome/src/main/java/com/roome/domain/cdcomment/notificationEvent/CdCommentCreatedEvent.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/main/java/com/roome/domain/guestbook/notificationEvent/GuestBookCreatedEvent.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/houseMate/notificationEvent/HouseMateCreatedEvent.java, roome/src/main/java/com/roome/domain/houseMate/repository/HousemateRepository.java, roome/src/main/java/com/roome/domain/houseMate/service/HousemateService.java, roome/src/main/java/com/roome/domain/notification/dto/CreateNotificationRequest.java, roome/src/main/java/com/roome/domain/notification/dto/NotificationMessage.java, roome/src/main/java/com/roome/domain/notification/service/NotificationWebSocketService.java, roome/src/main/java/com/roome/global/config/WebSocketConfig.java, roome/src/main/java/com/roome/global/notificationEvent/NotificationEvent.java, roome/src/test/java/com/roome/domain/notification/listener/NotificationEventListenerTest.java, roome/src/test/java/com/roome/domain/user/service/UserProfileServiceTest.java, roome/src/test/java/com/roome/global/notificationEvent/NotificationEventTest.java
Refactor/ 알림 발생 시 알리 발생 시간 제공 기능 수정 및 테스트 코드 커버리지 100 완료.
- 알림 이벤트 변경 클래스 및 서비스 코드 변경, 알림 생성 Dto 변경
=> Refactor/ 알림 발생 시 알리 발생 시간 제공 기능 수정 및 테스트 코드 커버리지 100 완료.

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
=> refactor: CD 댓글 API 경로 통일 및 파라미터 명칭 변경 (query → keyword)

roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java, roome/src/main/java/com/roome/domain/mycd/dto/MyCdListResponse.java, roome/src/main/java/com/roome/domain/mycd/exception/MyCdUnauthorizedException.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
CD 관련 기능 개선 및 최적화 작업을 수행하였습니다.
- CD 삭제 시 권한 검증 추가 및 예외 처리 강화
- CD 목록 조회 시 첫 번째 및 마지막 myCdId 반환 (페이지네이션 개선)
- MyCd 중복 추가 검증 최적화 (Repository 메서드 추가 및 중복 체크 개선)
> #244 
=> Refactor: CD 삭제 시 권한 검증 추가 및 조회/검색/중복 체크 최적화

roome/src/main/java/com/roome/domain/room/entity/RoomThemeUnlock.java, roome/src/main/java/com/roome/domain/room/repository/RoomThemeUnlockRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
=> Feat: 테마 변경 전, 잠긴 테마면 구매 로직 추가

roome/src/main/java/com/roome/domain/guestbook/controller/MockGuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java
다시 시간까지 나오게 변경 및 관계 최신 반영하도록 수정
=> Fix: 다시 시간까지 나오게 변경 및 관계 최신 반영하도록 수정

roome/src/main/java/com/roome/domain/payment/controller/PaymentController.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/payment/service/TossPaymentClient.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java
=> Feat: 환불 로직 추가

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/houseMate/service/HousemateService.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/main/java/com/roome/domain/rank/controller/RankingController.java, roome/src/main/java/com/roome/domain/rank/dto/UserRankingDto.java, roome/src/main/java/com/roome/domain/rank/entity/ActivityType.java, roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java, roome/src/main/java/com/roome/domain/rank/service/RankingService.java, roome/src/main/java/com/roome/domain/rank/service/UserActivityService.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/test/java/com/roome/domain/rank/service/UserActivityServiceTest.java
사용자의 다양한 활동을 추적하고 점수를 부여하는 랭킹 시스템을 구현했습니다.
=> Feat: 사용자 활동 기반 랭킹 시스템 구현

roome/src/main/java/com/roome/domain/point/entity/PointReason.java, roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java, roome/src/test/java/com/roome/domain/mybook/controller/MyBookControllerTest.java, roome/src/test/java/com/roome/domain/mybook/entity/repository/MyBookRepositoryTest.java, roome/src/test/java/com/roome/domain/mybook/service/MyBookServiceTest.java, roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java, roome/src/test/java/com/roome/domain/rank/service/RankingSchedulerTest.java, roome/src/test/java/com/roome/domain/room/controller/RoomControllerTest.java
=> fix: 테스트 코드 에러 수정

roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/point/controller/PointController.java, roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java, roome/src/main/java/com/roome/domain/point/repository/PointRepository.java, roome/src/main/java/com/roome/domain/point/service/PointService.java, roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java
포인트 도메인에서 예외 처리/코드 정리했습니다
- 매일 LocalDateTime.now()를 사용할 필요 없이 SQL CURRENT_DATE로 체크 → 쿼리 성능 최적화
- 중복 적립 방지를 위해 DB 인덱스 추가 가능 (user_id + reason + created_at)
- 조회 비용 최소화 (existsRecentEarned는 SELECT COUNT 사용)
=> Refactor: 포인트 도메인 예외 처리/코드 정리

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/room/entity/Room.java
=> Fix: 동시성 문제 해결

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/payment/controller/PaymentController.java, roome/src/main/java/com/roome/domain/payment/entity/Payment.java, roome/src/main/java/com/roome/domain/room/entity/Room.java
paymentKey nullable true로 변경했습니다.
> 결제 요청하면 아직 paymentKey 발급이 안 된 상태인데, nullable false 로 해두니까 db 에러 나서 수정했습니다
=> Fix: paymentKey nullable true로 변경

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/domain/auth/dto/response/LoginResponse.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java, roome/src/test/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandlerTest.java
사용자 정보 조회 api 호출 시, 유저 정보에 가구 레벨 응답 추가
=> Feat: 사용자 정보 반환 시 가구 레벨 응답 추가

roome/src/main/java/com/roome/domain/houseMate/service/HousemateService.java
=> Fix: 하우스메이트 500 에러로 인한 임시 주석

roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/payment/service/TossPaymentClient.java, roome/src/main/java/com/roome/domain/point/entity/Point.java, roome/src/main/java/com/roome/domain/point/entity/PointReason.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceTest.java, roome/src/test/java/com/roome/domain/room/controller/MockRoomControllerTest.java, roome/src/test/java/com/roome/domain/room/service/RoomServiceTest.java
결제 후 포인트 적립 시 포인트 도메인 활용하도록 수정했습니다.
=> Refactor: 결제 후 포인트 적립 시 포인트 도메인 활용하도록 수정

roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/payment/service/TossPaymentClient.java, roome/src/main/java/com/roome/domain/point/entity/Point.java, roome/src/main/java/com/roome/domain/point/entity/PointReason.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/repository/RoomThemeUnlockRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceTest.java, roome/src/test/java/com/roome/domain/room/controller/MockRoomControllerTest.java, roome/src/test/java/com/roome/domain/room/service/RoomServiceTest.java
=> Feat: 잠금 해제된 테마 조회 기능 추가

roome/src/main/java/com/roome/domain/payment/service/PaymentService.java
=> Fix: */ 제거

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java
=> Fix: room userId 받는 방식 변경

docker-compose-prod.yml, roome/src/main/java/com/roome/domain/notification/service/NotificationService.java
refactor: NotificationService.java 알림이 생성될 때 사용자 이름으로 생성되는걸 닉네임으로 수정. chesthyeon 3분 전
=> refactor: NotificationService.java 알림이 생성될 때 사용자 이름으로 생성되는걸 닉네임으로 수정. chesthyeon 3분 전

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
=> Fix: 방명록 여러 번 작성 가능하게 수정

.github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, docker-compose-prod.yml
=> 배포환경 및 개발환경 컨테이너 네트워크 분리

roome/src/main/java/com/roome/domain/guestbook/controller/GuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/point/service/PointService.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
=> Fix: 포인트 중복 결제 가능하게 수정

docker-compose-prod.yml, roome/src/main/java/com/roome/global/config/AsyncConfig.java
refactor: AsyncConfig.java 비동기 처리 빈 추가. chesthyeon 2분 전
=> refactor: AsyncConfig.java 비동기 처리 빈 추가. chesthyeon 2분 전

roome/src/main/java/com/roome/domain/furniture/dto/FurnitureRequestDto.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/controller/RoomController.java, roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/room/repository/RoomThemeUnlockRepository.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java, roome/src/test/java/com/roome/domain/room/controller/MockRoomControllerTest.java, roome/src/test/java/com/roome/domain/room/controller/RoomControllerTest.java, roome/src/test/java/com/roome/domain/room/service/RoomServiceTest.java
=> Test: room 테스트 코드 전체적으로 수정

roome/src/main/java/com/roome/domain/recommendedUser/entity/RecommendedUser.java, roome/src/main/java/com/roome/domain/recommendedUser/repository/RecommendedUserRepository.java, roome/src/main/java/com/roome/domain/recommendedUser/service/RecommendedUserService.java, roome/src/main/java/com/roome/domain/user/service/UserProfileService.java, roome/src/main/java/com/roome/domain/userGenrePreference/repository/UserGenrePreferenceRepository.java, roome/src/main/java/com/roome/global/config/BatchSchedulerConfig.java, roome/src/main/java/com/roome/global/config/InitialDataLoader.java
recommended users 테이블을 생성하여 사용자 추천 로직 최적화
=> Feat/recommended users 테이블을 생성하여 사용자 추천 로직 최적화

roome/src/main/java/com/roome/domain/payment/service/PaymentService.java
=> Fix: 페이지 조회 1페이지 시작으로 변경

roome/src/main/java/com/roome/domain/payment/dto/PaymentLogResponseDto.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/point/service/PointService.java
=> Fix: 결제 상태도 조회되게 수정

roome/src/main/java/com/roome/domain/payment/dto/PaymentLogResponseDto.java, roome/src/main/java/com/roome/domain/payment/entity/PaymentLog.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java, roome/src/main/java/com/roome/domain/point/service/PointService.java
=> Fix: 결제 환불도 조회 되게 수정

roome/src/main/resources/application.yml
=> Refactor: db 초기화

roome/src/main/java/com/roome/domain/houseMate/controller/HousemateController.java, roome/src/main/java/com/roome/domain/houseMate/controller/MockHouseMateController.java, roome/src/main/java/com/roome/domain/houseMate/dto/HousemateInfo.java, roome/src/main/java/com/roome/domain/houseMate/dto/HousemateListResponse.java, roome/src/main/java/com/roome/domain/houseMate/repository/HousemateRepositoryImpl.java, roome/src/main/java/com/roome/domain/houseMate/service/HousemateService.java
fix: 내가 추가한 유저 목록에서 상대방 아이디가 보이지 않는 오류 수정. chesthyeon 14분 전
=> fix: 내가 추가한 유저 목록에서 상대방 아이디가 보이지 않는 오류 수정. chesthyeon 14분 전

roome/src/main/resources/application.yml
=> Fix: google redirect uri 변경

roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationFailureHandler.java, roome/src/main/resources/application.yml
=> Feat: oauth2 인증 실패 응답 개선

.github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, docker-compose-prod.yml, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/resources/application.yml
=> 기본 사이트 인증 인가 허용

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java, roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
- 조회 메서드에 `@Transactional(readOnly = true)` 추가하여 성능 최적화
- `CdCommentRepository` 개선:
- 대소문자 구분 없이 검색하도록 `COLLATE utf8mb4_general_ci` 적용
- `findByMyCdIdAndKeyword` 쿼리 성능 향상
- 댓글 저장 시 내용 앞뒤 공백 제거 (`trim()` 적용)
- 로깅 추가로 디버깅 편의성 향상
> #357 
=> Refactor: Spring 트랜잭션 적용 및 CD 댓글 조회 로직 최적화

roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java
=> Fix: 방명록 작성자와 방 주인이 삭제할 수 있도록 수정

roome/src/main/java/com/roome/domain/houseMate/repository/HousemateRepository.java, roome/src/main/java/com/roome/domain/recommendedUser/service/RecommendedUserService.java
=> fix : 추천 사용자에 이미 등록된 하우스 메이트는 안 나오게 수정

roome/src/main/java/com/roome/domain/mybook/entity/MyBookQueryModel.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookCountRedisRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookIdsRedisRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookQueryModelRedisRepository.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybook/service/response/MyBookResponse.java, roome/src/main/java/com/roome/domain/mybook/service/response/MyBooksResponse.java, roome/src/main/java/com/roome/domain/mybookreview/controller/MockMyBookReviewController.java, roome/src/main/java/com/roome/domain/mybookreview/entity/MyBookReviewQueryModel.java, roome/src/main/java/com/roome/domain/mybookreview/entity/repository/MyBookReviewQueryModelRedisRepository.java, roome/src/main/java/com/roome/domain/mybookreview/service/MyBookReviewService.java, roome/src/main/java/com/roome/domain/mybookreview/service/response/MyBookReviewResponse.java, roome/src/main/java/com/roome/domain/rank/service/RankingService.java, roome/src/main/java/com/roome/global/dataserializer/DataSerializer.java
=> Refactor: 랭킹 10위안의 유저의 MyBook, MyBookReview에 redis를 이용한 캐싱 적용

roome/build.gradle, roome/src/main/java/com/roome/domain/point/controller/PointController.java, roome/src/main/java/com/roome/domain/point/service/PointService.java, roome/src/main/java/com/roome/global/config/RedissonConfig.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/LockAcquisitionFailedException.java, roome/src/main/java/com/roome/global/service/RedisLockService.java
- Redis 분산락(Redisson)을 이용해 포인트 적립 및 사용 시 동시성 문제 해결
- 포인트 적립 및 사용 이후 Redis 캐시를 즉시 갱신하여 최신 데이터 유지
=> Feat: 포인트 시스템 동시성 처리

roome/src/main/java/com/roome/RoomeApplication.java, roome/src/main/java/com/roome/domain/rank/entity/ScoreUpdateTask.java, roome/src/main/java/com/roome/domain/rank/entity/TaskStatus.java, roome/src/main/java/com/roome/domain/rank/repository/ScoreUpdateTaskRepository.java, roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java, roome/src/main/java/com/roome/domain/rank/service/ScoreRecoveryService.java, roome/src/main/java/com/roome/domain/rank/service/UserActivityService.java, roome/src/main/java/com/roome/global/config/AsyncConfig.java, roome/src/main/java/com/roome/global/service/RedisService.java
랭킹 시스템의 동시성 이슈를 해결하고 성능을 개선하기 위해 비동기 처리와 분산락을 적용했습니다. 
=> Refactor: 랭킹 시스템 성능 개선

roome/src/main/java/com/roome/domain/user/service/UserService.java
RoomThemeUnlock 관련 데이터 삭제 로직을 추가해 외래 키 제약 조건 오류 해결
=> Fix: RoomThemeUnlock 관련 데이터 삭제 로직 추가

roome/src/main/java/com/roome/domain/rank/service/RankingService.java, roome/src/main/java/com/roome/global/config/RedisConfig.java
랭킹 시스템 전용 StringRedisTemplate을 추가해 Redis 데이터 타입 불일치 문제 해결
=> Fix: 랭킹 시스템 Redis 데이터 타입 불일치 문제 해결

roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java, roome/src/main/java/com/roome/global/service/RedisService.java
RankingScheduler와 RedisService에서 rankingRedisTemplate를 일괄 적용 레디스 데이터 불일치 오류 해결
=> Fix: Redis 랭킹 데이터 직렬화 일관성 적용

roome/src/main/java/com/roome/domain/point/controller/PointController.java, roome/src/main/java/com/roome/domain/point/dto/PointHistoryGroupedDto.java, roome/src/main/java/com/roome/domain/point/dto/PointHistoryResponse.java, roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java, roome/src/main/java/com/roome/domain/point/service/PointService.java
=> Feat: 포인트 내역 조회 커서 기반 페이징 개선

roome/src/main/java/com/roome/domain/guestbook/repository/GuestbookRepository.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java
=> Fix: 방명록 관계 에러 수정

roome/src/main/java/com/roome/domain/cdtemplate/entity/CdTemplate.java, roome/src/main/java/com/roome/domain/cdtemplate/repository/CdTemplateRepository.java, roome/src/main/java/com/roome/domain/cdtemplate/service/CdTemplateService.java
=> Feat: cd_template 테이블에 user_id 컬럼 추가 및 저장 로직 수정

roome/src/main/java/com/roome/domain/event/service/FirstComeEventScheduler.java
=> Chore: 타임어택 이벤트 시작 기간, 마감 인원 수정
