roome/.gitignore, roome/build.gradle, roome/src/main/java/com/roome/domain/oauth2/dto/KakaoResponse.java, roome/src/main/java/com/roome/domain/oauth2/dto/OAuth2UserPrincipal.java, roome/src/main/java/com/roome/domain/oauth2/exception/AuthenticationFailedException.java, roome/src/main/java/com/roome/domain/oauth2/exception/DisabledAccountException.java, roome/src/main/java/com/roome/domain/oauth2/exception/InvalidLoginException.java, roome/src/main/java/com/roome/domain/oauth2/exception/Oauth2AuthenticationErrorException.java, roome/src/main/java/com/roome/domain/oauth2/exception/UnsupportedOAuth2ProviderException.java, roome/src/main/java/com/roome/domain/oauth2/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/oauth2/service/OAuth2Factory.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/BusinessException.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java, roome/src/main/java/com/roome/global/jwt/controller/AuthController.java, roome/src/main/java/com/roome/global/jwt/dto/JwtToken.java, roome/src/main/java/com/roome/global/jwt/exception/InvalidJwtTokenException.java, roome/src/main/java/com/roome/global/jwt/exception/InvalidRefreshTokenException.java, roome/src/main/java/com/roome/global/jwt/exception/MissingAuthorityException.java, roome/src/main/java/com/roome/global/jwt/exception/UserNotFoundException.java, roome/src/main/java/com/roome/global/jwt/filter/JwtAuthenticationFilter.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2FailureHandler.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2SuccessHandler.java, roome/src/main/java/com/roome/global/jwt/helper/TokenResponseHelper.java, roome/src/main/java/com/roome/global/jwt/service/JwtTokenProvider.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/main/resources/application.yml
Feat: OAuth2 로그인 및 JWT 기반 인증/인가 기능 구현
- OAuth2 로그인 후 JWT를 발급하고, 이를 이용한 인증 및 인가 로직 구축
- Refresh Token을 이용한 Access Token 재발급 기능 추가
#3, #4, #5 
=> Feat: OAuth2 로그인 및 JWT 기반 인증/인가 기능 구현

roome/src/main/java/com/roome/domain/cd/entity/Cd.java, roome/src/main/java/com/roome/domain/cd/entity/CdComment.java, roome/src/main/java/com/roome/domain/cd/entity/CdPlayer.java, roome/src/main/java/com/roome/domain/cd/entity/CdTemplate.java
- 엔티티 클래스 작성
- Cd 엔티티 생성 (사용자가 추가한 CD 정보 저장)
- CdPlayer 엔티티 생성 (사용자의 CD 플레이어 - CD 목록)
- CdTemplate 엔티티 생성 (CD에 대한 템플릿)
- CdComment 엔티티 생성 (CD에 대한 댓글)
> #10 
> 이슈에서 작성했던 엔티티에서 필요 없는 엔티티 삭제, 이름 수정
=> feat: CD 관련 엔티티 추가

roome/build.gradle, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/config/SwaggerConfig.java, roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java
스웨거 연동 해뒀습니다.
> 기존 500 에러는 swagger와 spring boot 버전이 호환이 안 돼서 발생하던 거였는데, 해결 방법이 없다고 합니다 ..ㅎㅎ
스프링 부트 버전을 낮추는 방법 말고는 `GlobalExceptionHandler`에 있는 `@RestControllerAdvice`를 주석처리 해서 임시로 제거 해주는게 있는데, 이렇게 하면 에러 코드가 상당히 길고 지저분하게 나오게 됩니다 ㅠㅠ ..
`@RestControllerAdvice` 이거 때문에 충돌이 발생하는 거라서 스웨거로 확인하실 땐 저 부분 주석처리 하고 사용하시고, 그 외에는 다시 주석 해제해서 에러코드 정상적으로 나오게 계속 바꿔줘야 할 듯 합니다 ....
=> Feat: 스웨거 연동

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/domain/auth/dto/oauth2/OAuth2Provider.java, roome/src/main/java/com/roome/domain/auth/dto/request/LoginRequest.java, roome/src/main/java/com/roome/domain/auth/exception/MissingAuthorizationCodeException.java, roome/src/main/java/com/roome/domain/auth/service/OAuth2LoginService.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java
AuthController 테스트 추가
- OAuth2ClientProperties 및 SecurityConfig를 정리하여 코드 가독성을 개선
- JWT 토큰 재발급 시 providerId 대신 userId를 사용하여 사용자 조회 로직 변경
- AuthControllerTest에서 로그인 요청 관련 테스트를 추가하고 예외 처리를 개선
=> AuthController 테스트 추가

roome/build.gradle, roome/src/main/java/com/roome/domain/auth/dto/oauth2/GoogleResponse.java, roome/src/main/java/com/roome/domain/auth/dto/oauth2/KakaoResponse.java, roome/src/main/java/com/roome/domain/auth/dto/oauth2/NaverResponse.java, roome/src/main/java/com/roome/domain/auth/dto/oauth2/OAuth2Provider.java, roome/src/main/java/com/roome/domain/auth/dto/oauth2/OAuth2Response.java, roome/src/main/java/com/roome/domain/auth/security/OAuth2UserPrincipal.java, roome/src/main/java/com/roome/domain/auth/service/OAuth2Factory.java, roome/src/main/java/com/roome/domain/auth/service/OAuth2LoginService.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2SuccessHandler.java, roome/src/main/java/com/roome/global/jwt/service/JwtTokenProvider.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/auth/service/OAuth2LoginServiceTest.java, roome/src/test/java/com/roome/global/jwt/service/JwtTokenProviderTest.java, roome/src/test/java/com/roome/global/jwt/service/TokenServiceTest.java
JWT 및 OAuth2 인증 로직을 개선하고, 관련 테스트를 추가하였습니다.
=> Refactor: JWT 및 OAuth2 인증 로직 개선 및 테스트 추가

roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java, roome/src/main/java/com/roome/domain/cdcomment/controller/MockCdCommentController.java, roome/src/main/java/com/roome/domain/cdtemplate/controller/CdTemplateController.java, roome/src/main/java/com/roome/domain/cdtemplate/controller/MockCdTemplateController.java, roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java, roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java
MyCd, CdComment, CdTemplate 도메인의 API 경로를 기존 카멜 케이스(Camel Case) → **케밥 케이스(Kebab Case)**로 변경하였습니다.
> #126 
> 패키지명(com.roome.domain.mycd)은 유지하고, API 엔드포인트(URL)만 케밥 케이스로 변경했습니다.
=> Refactor: mycd, cdcomment, cdtemplate 케밥 케이스 적용

roome/build.gradle, roome/src/main/java/com/roome/RoomeApplication.java, roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/global/config/CacheConfig.java, roome/src/main/java/com/roome/global/config/RedisConfig.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/exception/ErrorCode.java, roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java, roome/src/main/java/com/roome/global/jwt/exception/InvalidUserIdFormatException.java, roome/src/main/java/com/roome/global/jwt/exception/MissingUserIdFromTokenException.java, roome/src/main/java/com/roome/global/jwt/filter/JwtAuthenticationFilter.java, roome/src/main/java/com/roome/global/jwt/service/JwtTokenProvider.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/main/java/com/roome/global/service/RedisService.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java, roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java, roome/src/test/java/com/roome/global/jwt/service/TokenServiceTest.java
Redis를 활용한 인증/인가 로직을 적용하고, Refresh Token 및 Access Token 관리를 강화하였습니다.
> Redis를 활용한 인증/인가 로직이 추가됨에 따라, 로컬에서 Redis가 실행 중인지 확인 필요
=> Feat: Redis 기반 인증/인가 로직 및 보안 설정 추가

roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/domain/user/repository/UserRepository.java
=> Fix: 마지막 로그인 시간 업데이트 쿼리 수정, 마지막 로그인 시간 비교시 NPE 발생하지 않도록 비교 순서 변경

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/config/SwaggerConfig.java, roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java, roome/src/main/resources/application.yml, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java, roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java, roome/src/test/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandlerTest.java
프론트엔드와 백엔드 간 원활한 인증 연동을 위해 OAuth2 로그인 후 리다이렉트 방식을 도입하고 토큰 관리 방식을 개선했습니다.
> 프론트엔드에서는 OAuth2 로그인 버튼 클릭 시 백엔드 /oauth2/authorization/{provider} 엔드포인트로 요청을 보내야 합니다.
인증 성공 시 http://localhost:5173/oauth/callback?accessToken=xxxx&userId=123 형태로 리다이렉트됩니다.
프론트엔드는 액세스 토큰을 저장하고 /api/auth/user API를 호출하여 사용자 정보와 리프레시 토큰을 얻을 수 있습니다.
액세스 토큰 만료 시 /api/auth/reissue-token API를 호출하여 새 토큰을 발급받아야 합니다.
=> Feat: 프론트엔드 연동을 위한 인증 시스템 개선

roome/src/main/java/com/roome/domain/cdtemplate/controller/CdTemplateController.java, roome/src/test/java/com/roome/domain/cdtemplate/controller/CdTemplateControllerTest.java
- CdTemplateController에 인증 기능을 적용하고, 관련 테스트 코드를 수정하였습니다.
- @AuthenticatedUser를 적용하여 userId 자동 주입
- 템플릿 생성, 수정, 삭제 API에 인증 적용
- CdTemplateControllerTest에서 userId 관련 테스트 수정 및 보완
> 
> #161 
=> feat: CdTemplateController에 @AuthenticatedUser 적용 및 테스트 코드 수정

roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java, roome/src/test/java/com/roome/global/jwt/controller/ReissueControllerTest.java
PointHistoryRepository를 Mock으로 추가하여 NullPointerException을 해결하고, 리프레시 토큰을 이용한 액세스 토큰 재발급 테스트를 추가했습니다.
=> Test: OAuth2 로그인 및 토큰 재발급 테스트 수정 및 추가

roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/main/java/com/roome/global/jwt/dto/TokenReissueRequest.java, roome/src/main/resources/application.yml
SecurityConfig에 defaultSuccessUrl를 추가하여 success handler 실행
=> Feat: OAuth2 로그인 리다이렉트 설정 변경 및 SecurityConfig 기본 설정 추가 

roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/global/config/SecurityConfig.java, roome/src/main/java/com/roome/global/config/SwaggerConfig.java, roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/main/java/com/roome/global/jwt/dto/TokenResponse.java, roome/src/main/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandler.java, roome/src/main/java/com/roome/global/jwt/service/JwtTokenProvider.java, roome/src/main/java/com/roome/global/jwt/service/TokenService.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java, roome/src/test/java/com/roome/global/jwt/controller/ReissueControllerTest.java, roome/src/test/java/com/roome/global/jwt/handler/OAuth2AuthenticationSuccessHandlerTest.java, roome/src/test/java/com/roome/global/jwt/service/TokenServiceTest.java
=> Feat: OAuth2 인증 및 JWT 토큰 관리 개선

roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java, roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java, roome/src/main/java/com/roome/domain/mycd/dto/MyCdListResponse.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/test/java/com/roome/domain/mycd/controller/MyCdControllerTest.java, roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
MyCd 목록 조회 시 CD 제목 또는 가수명(keyword)으로 검색하는 기능을 추가하고, 검색된 결과의 총 개수를 반환하는 기능을 구현하였습니다.
또한, 테스트 코드 추가 및 커버리지 개선을 진행했습니다.
- MyCd 목록 조회 시 키워드 검색 기능 추가
- 검색된 결과의 전체 개수 반환 기능 추가
- 테스트 코드 추가 및 커버리지 개선
> <img width="632" alt="스크린샷 2025-02-28 11 22 15" src="https://github.com/user-attachments/assets/b2e723e5-aba8-47b9-946a-be83ebc63dcc" />
> #187 
=> Feat: MyCd 목록 조회 시 검색 기능 및 총 개수 반환 기능 추가

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/user/entity/User.java
user와 room 엔티티를 수정하여 userId와 roomId를 동일하게 설정하고, getOrCreateRoomByUserId 메서드를 삭제하여 불필요한 로직을 정리했습니다.
> 기존 getOrCreateRoomByUserId를 사용하던 부분이 있다면 getRoomByUserId로 변경 필요
=> Refactor: user, room 엔티티 수정 및 getOrCreateRoomByUserId 삭제

roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
MyCdServiceTest 테스트 커버리지 100% 보장했습니다.
- getMyCdList()에서 빈 리스트 반환 허용
- cursor가 null 또는 0일 때 findByUserIdOrderByIdAsc()가 호출되도록 로직 확인
- Optional.ofNullable().orElseGet(Page.empty(pageable)) 적용하여 null 반환 방지
- MyCdServiceTest에 cursor == null 및 cursor == 0 케이스 추가
- 테스트 커버리지 개선
> ![image](https://github.com/user-attachments/assets/8d603963-cc36-4514-b301-d99b15b2cfe9)
> #203 
=> feat: MyCdService 개선 및 테스트 커버리지 향상

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/user/repository/UserRepository.java, roome/src/test/java/com/roome/domain/auth/service/CustomOAuth2UserServiceTest.java
소셜 로그인 시 사용자 식별 로직을 변경했습니다. 소셜 로그인 시 이메일 대신 provider +provider id 조합으로 사용자를 식별하도록 변경했습니다.
> 모든 테스트가 성공적으로 동작했습니다. 새로운 소셜 로그인 식별 로직이 정상 작동하는 것을 확인했습니다.
=> Refactor: 소셜 로그인 사용자 식별 로직 개선

roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java
=> Fix: 방 조회시 방 주인의 닉네임도 응답되도록 수정

roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
- `targetUserId` 요청 파라미터 추가하여 특정 사용자의 CD 목록 조회 가능하도록 변경
- `targetUserId`가 없을 경우, 기본적으로 로그인한 사용자의 목록을 조회하도록 설정
- 기존 `userId` 기반 요청을 `targetUserId`로 변경하여 API 일관성 유지
- 로그 추가 (`log.info()`)로 요청한 사용자와 조회 대상 사용자 구분 가능하도록 개선"
=> feat: CD 목록 조회 시 로그인한 사용자와 조회 대상 사용자 구분 가능하도록 수정

roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
특정 CD 조회 시 targetUserId를 적용하여 다른 사용자의 MyCd도 조회할 수 있도록 수정했습니다.
> #237 
=> Feat: 특정 CD 조회 시 targetUserId 적용 기능 추가

roome/build.gradle, roome/src/main/java/com/roome/RoomeApplication.java, roome/src/main/java/com/roome/domain/auth/controller/AuthController.java, roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/guestbook/repository/GuestbookRepository.java, roome/src/main/java/com/roome/domain/houseMate/repository/HousemateRepository.java, roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java, roome/src/main/java/com/roome/domain/point/repository/PointRepository.java, roome/src/main/java/com/roome/domain/room/entity/Room.java, roome/src/main/java/com/roome/domain/user/entity/User.java, roome/src/main/java/com/roome/domain/user/service/UserService.java, roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java, roome/src/main/java/com/roome/global/service/RedisService.java, roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java, roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java, roome/src/test/java/com/roome/domain/user/service/UserServiceTest.java, roome/src/test/java/com/roome/global/service/RedisServiceTest.java
회원 탈퇴 시 500 에러가 나던 문제를 개선하기 위해, 회원 탈퇴 및 Redis 관련 로직을 수정하고, 예외 처리 및 트랜잭션 안정성을 향상시켰습니다.
> 
> 회원가입/로그인 에러로 createDefaultFurnitures() 메서드 주석 처리하였습니다.
=> Feat: 회원 탈퇴 로직 개선 및 Redis 재시도 적용

roome/src/main/java/com/roome/domain/mycd/exception/MyCdDatabaseException.java, roome/src/main/java/com/roome/domain/mycd/exception/MyCdPaginationException.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
CD 목록 조회 API의 데이터 반환 로직을 개선하여 프론트엔드에서 요청한 형식과 맞도록 수정하였습니다.
이제 유저가 등록한 전체 CD 중에서 가장 첫 번째(firstMyCdId), 마지막(lastMyCdId) CD ID를 반환합니다.
또한, 예외 처리를 추가하여 안정성을 높였습니다.
- firstMyCdId, lastMyCdId: 유저가 등록한 전체 CD 중에서 첫 번째, 마지막 ID를 반환하도록 변경
- MyCdDatabaseException, MyCdPaginationException 예외 추가 및 적용
- MyCdRepository에 `findFirstByUserIdOrderByIdAsc`, `findFirstByUserIdOrderByIdDesc` 메서드 추가
- 잘못된 커서 값 처리 (`MyCdPaginationException` 적용)
> #246 
=> Refactor: CD 목록 조회 API의 totalCount, firstMyCdId, lastMyCdId 개선

roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mybookreview/entity/repository/MyBookReviewRepository.java
MyBook 삭제 안되는 문제 해결
MyBook과 MyBookReview가 1:1관계인데, MyBookReveiw가 있으면 MyBook이 삭제가 안되고 있던 문제, MyBookReview 먼저 삭제 후 MyBook 삭제
=> Fix: MyBook 삭제전, MyBookReview 먼저 삭제

roome/src/main/java/com/roome/domain/book/entity/repository/GenreRepository.java, roome/src/main/java/com/roome/domain/cd/repository/CdGenreTypeRepository.java, roome/src/main/java/com/roome/domain/furniture/dto/FurnitureResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/controller/MockGuestbookController.java, roome/src/main/java/com/roome/domain/guestbook/dto/GuestbookResponseDto.java, roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/room/controller/MockRoomController.java, roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java, roome/src/main/java/com/roome/domain/room/service/RoomService.java
=> Fix: 방명록 응답 수정 및 가구 응답 수정

roome/src/main/java/com/roome/domain/room/dto/RoomResponseDto.java
방 조회 시 닉네임이랑 생성 날짜도 응답되도록 수정했습니다.
=> Fix: 방 조회 시 닉네임이랑 생성 날짜도 응답되도록 수정

roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java, roome/src/main/java/com/roome/domain/point/service/PointService.java, roome/src/main/java/com/roome/domain/user/entity/User.java
=> Fix: 하루마다 첫 로그인시 포인트 적립 안되던 문제 해결

roome/src/main/java/com/roome/domain/mybook/controller/MyBookController.java, roome/src/main/java/com/roome/domain/mybook/entity/repository/MyBookRepository.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java
등록 도서 목록조회 API에 keyword 추가, 제목, 저자, 출판사에 대한 검색 가능
=> Feat: 등록 도서 목록조회 API에 keyword 추가, 제목, 저자, 출판사에 대한 검색 가능

roome/src/main/java/com/roome/domain/point/entity/PointReason.java, roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java, roome/src/test/java/com/roome/domain/rank/service/RankingSchedulerTest.java
Point 도메인을 활용하도록 랭킹 보상 지급 로직을 수정했습니다.
> #275
=> Refactor: 주간 랭킹 보상 시스템 개선

roome/src/main/java/com/roome/domain/event/controller/FirstComeEventController.java, roome/src/main/java/com/roome/domain/event/dto/FirstComeEventResponse.java, roome/src/main/java/com/roome/domain/event/entity/EventStatus.java, roome/src/main/java/com/roome/domain/event/entity/FirstComeEvent.java, roome/src/main/java/com/roome/domain/event/repository/FirstComeEventRepository.java, roome/src/main/java/com/roome/domain/event/service/FirstComeEventScheduler.java, roome/src/main/java/com/roome/domain/event/service/FirstComeEventService.java
선착순 이벤트를 자동 생성하고, 사용자가 참여할 수 있도록 기능을 구현했습니다.
=> Feat: 선착순 이벤트 상태 관리 방식 개선 및 조회 기능 추가 

roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java, roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java, roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
CdComment 테스트 코드 개선했습니다.
- CdCommentControllerTest 추가 및 테스트 커버리지 100% 달성
- CdCommentServiceTest에서 모든 주요 메서드 테스트, 커버리지 92% 달성
- 댓글 조회(getComments)에서 키워드 여부에 따른 테스트 추가
- PageRequest 음수 인덱스 방지 처리 추가
- 이벤트 발행(`ApplicationEventPublisher`) 및 사용자 활동 기록(`UserActivityService`) Mock 처리하여 안정성 개선
> 
> #292 
=> Test: CdCommentController & CdCommentService 테스트 커버리지 개선

roome/src/main/java/com/roome/domain/houseMate/service/HousemateService.java, roome/src/main/java/com/roome/domain/rank/service/UserActivityService.java, roome/src/test/java/com/roome/domain/rank/service/RankingSchedulerTest.java, roome/src/test/java/com/roome/domain/rank/service/UserActivityServiceTest.java, roome/src/test/java/com/roome/global/jwt/controller/ReissueControllerTest.java
팔로우 활동 기록 시 발생하는 예외가 핵심 비즈니스 로직에 영향을 주지 않도록 try-catch문으로 예외 처리 강화
> ✅ 하우스메이트 추가 동작 확인
✅ 하우스메이트 추가 / 점수 지급 확인
✅ mariaDB / Redis 팔로워 점수 지급 확인
✅ UserActivityServiceTest 동작 확인
=> Fix: 하우스메이트 추가 시 랭킹 점수 부여 로직 개선

roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java, roome/src/main/java/com/roome/domain/point/service/PointService.java
포인트 내역 조회 시 전체 데이터 기준의 firstId / lastId를 별도로 조회
- 기존에는 firstId와 lastId가 조회된 데이터 기준으로 설정됨
- firstId를 전체 포인트 내역 중 가장 최신 ID (MAX)로 설정
- lastId를 전체 포인트 내역 중 가장 오래된 ID (MIN)로 설정
- 관련 쿼리를 PointHistoryRepository에 추가하여 firstId/lastId 조회 처리
> #306 
=> Fix: 포인트 내역 조회 시 firstId, lastId를 전체 기준으로 변경

roome/src/main/java/com/roome/domain/notification/service/NotificationService.java, roome/src/main/resources/application.yml
refactor: NotificationService.java 이벤트 알림의 경우 발신자 및 수신자 id 검증을 하지 않도록 수정 chesthyeon 2분 전
=> Feat/event/297 refactor: NotificationService.java 이벤트 알림의 경우 발신자 및 수신자 id 검증을 하지 않도록 수정 및 DB 초기화 셋팅

docker-compose-prod.yml, roome/src/main/java/com/roome/domain/mybook/event/BookCollectionEvent.java, roome/src/main/java/com/roome/domain/mybook/service/MyBookService.java, roome/src/main/java/com/roome/domain/mycd/event/CdCollectionEvent.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/main/java/com/roome/domain/user/service/UserProfileService.java, roome/src/main/java/com/roome/domain/userGenrePreference/entity/GenreType.java, roome/src/main/java/com/roome/domain/userGenrePreference/entity/UserGenrePreference.java, roome/src/main/java/com/roome/domain/userGenrePreference/listner/GenrePreferenceEventListener.java, roome/src/main/java/com/roome/domain/userGenrePreference/repository/UserGenrePreferenceRepository.java, roome/src/main/java/com/roome/domain/userGenrePreference/service/GenrePreferenceService.java, roome/src/test/java/com/roome/domain/userGenrePreference/listner/GenrePreferenceEventListenerTest.java, roome/src/test/java/com/roome/domain/userGenrePreference/service/GenrePreferenceServiceTest.java
=> feat: 유저 프로필 조회시에 장르 계산 서비스 개선

roome/src/main/java/com/roome/domain/mycd/repository/MyCdQueryRepository.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdQueryRepositoryImpl.java, roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java, roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java, roome/src/test/java/com/roome/domain/mycd/controller/MyCdControllerTest.java, roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
QueryDSL을 활용하여 MyCd 검색 기능을 최적화하고 기존 JPA 메서드를 개선하였습니다.
이전 대비 성능을 향상시키고, 키워드 검색 기능을 확장하였습니다.
> 
QueryDSL 적용 전후 성능 비교 (k6 테스트 결과)
- 평균 응답 시간 (http_req_duration)
- Before: 356.49ms
- After: 91.7ms (~74% 감소)
- P95 응답 속도
- Before: 644.81ms
- After: 23.73ms
- 처리량 (http_reqs/s)
- Before: 162 req/s
- After: 214 req/s (+21.6% 증가)
> #338 
=> Feat: QueryDSL 기반 검색 기능 추가 및 성능 최적화

roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java
- GlobalExceptionHandler에 ForbiddenException 핸들러 추가
- 500으로 처리되던 ForbiddenException을 명확히 403으로 반환하도록 수정
- MockMvc 테스트에서 예상 응답 코드(403)와 실제 응답 코드(500) 불일치 문제 해결
> #359 
=> Fix: ForbiddenException 발생 시 500 → 403으로 반환되도록 예외 처리 추가

roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java, roome/src/main/java/com/roome/domain/payment/service/PaymentService.java
환불해도 paymentKey는 똑같도록 수정 및 하우스메이트라고 뜨는 조건 변경
=> Fix: 환불해도 paymentKey는 똑같도록 수정 및 하우스메이트라고 뜨는 조건 변경

roome/src/main/java/com/roome/domain/cdtemplate/exception/DuplicateCdTemplateException.java, roome/src/main/java/com/roome/domain/cdtemplate/repository/CdTemplateRepository.java, roome/src/main/java/com/roome/domain/cdtemplate/service/CdTemplateService.java, roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
- `existsByMyCdId(myCdId)`를 사용하여 중복 체크 후 저장
- 동일한 `myCdId`가 존재하면 `DuplicateCdTemplateException` 발생
- 중복 데이터 방지 및 안정적인 템플릿 생성 로직 유지
- MyBookReviewControllerTest 테스트 코드 주석 처리
=> Feat: CdTemplate 중복 체크 후 저장 로직 추가

roome/src/main/java/com/roome/domain/payment/repository/PaymentLogRepository.java, roome/src/main/java/com/roome/domain/payment/repository/PaymentRepository.java, roome/src/main/java/com/roome/domain/user/service/UserService.java
회원 탈퇴 시 결제 데이터(Payment, PaymentLog) 연관 삭제 기능을 추가해 탈퇴 시에 발생하던 외래 키 제약 조건 문제를 해결했습니다.
=> Fix: 회원 탈퇴 시 외래 키 제약 조건 문제 해결
